// Package components provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package components

// DNSHostname defines model for DNSHostname.
type DNSHostname = string

// Error defines model for Error.
type Error struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

// ErrorString A human-readable error message.
type ErrorString = string

// IPv4Address defines model for IPv4Address.
type IPv4Address = string

// PortNumber defines model for PortNumber.
type PortNumber = int

// PortString defines model for PortString.
type PortString = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error
