//go:build go1.22

// Package rvto2addr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package rvto2addr

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
	BasicAuthScopes  basicAuthContextKey  = "BasicAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
	Oauth2AuthScopes oauth2AuthContextKey = "Oauth2Auth.Scopes"
	OidcAuthScopes   oidcAuthContextKey   = "OidcAuth.Scopes"
)

// RVTO2Addr Rendezvous TO2 address configuration. Specifies one or more owner server
// addresses that devices should use to connect during the TO2 (Transfer of
// Ownership 2) protocol after completing rendezvous. Multiple entries provide
// fallback options if the primary address is unreachable.
type RVTO2Addr = []RVTO2AddrEntry

// RVTO2AddrEntry A single owner server address entry. Each entry specifies the protocol,
// network location (DNS hostname and/or IP address), and port for connecting
// to the owner server during TO2 protocol.
//
// Both 'dns' and 'ip' fields are optional and may be provided independently
// or together. However, at least one addressing method MUST be specified
// (non-null) as required by FDO specification section 3.3.14. Requests that
// omit both 'dns' and 'ip' will be rejected with a 400 Bad Request error.
//
// When both 'dns' and 'ip' are provided, the device MUST attempt to connect
// using the DNS address first. The device MUST only use the IP address after
// all DNS connection attempts have failed. This behavior is defined in the
// FDO specification section 3.3.14.
type RVTO2AddrEntry struct {
	Dns  *externalRef0.DNSHostname `json:"dns,omitempty"`
	Ip   *externalRef0.IPv4Address `json:"ip,omitempty"`
	Port externalRef0.PortNumber   `json:"port"`

	// Protocol Protocol to use for communication:
	// - `rest` - RESTful HTTP/HTTPS
	// - `http` - HTTP protocol
	// - `https` - HTTPS protocol (recommended for production)
	// - `tcp` - Raw TCP connection
	// - `tls` - TLS-secured TCP connection
	// - `coap+tcp` - CoAP over TCP
	// - `coap` - Constrained Application Protocol
	Protocol externalRef0.ProtocolType `json:"protocol"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// basicAuthContextKey is the context key for BasicAuth security scheme
type basicAuthContextKey string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// oauth2AuthContextKey is the context key for Oauth2Auth security scheme
type oauth2AuthContextKey string

// oidcAuthContextKey is the context key for OidcAuth security scheme
type oidcAuthContextKey string

// UpdateRVTO2AddrJSONRequestBody defines body for UpdateRVTO2Addr for application/json ContentType.
type UpdateRVTO2AddrJSONRequestBody = RVTO2Addr

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete the RVTO2 address configuration
	// (DELETE /v1/rvto2addr)
	DeleteRVTO2Addr(w http.ResponseWriter, r *http.Request)
	// Get the current RVTO2 address configuration
	// (GET /v1/rvto2addr)
	GetRVTO2Addr(w http.ResponseWriter, r *http.Request)
	// Update the RVTO2 address configuration
	// (PUT /v1/rvto2addr)
	UpdateRVTO2Addr(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteRVTO2Addr operation middleware
func (siw *ServerInterfaceWrapper) DeleteRVTO2Addr(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRVTO2Addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRVTO2Addr operation middleware
func (siw *ServerInterfaceWrapper) GetRVTO2Addr(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRVTO2Addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRVTO2Addr operation middleware
func (siw *ServerInterfaceWrapper) UpdateRVTO2Addr(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRVTO2Addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/rvto2addr", wrapper.DeleteRVTO2Addr)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rvto2addr", wrapper.GetRVTO2Addr)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/rvto2addr", wrapper.UpdateRVTO2Addr)

	return m
}

type DeleteRVTO2AddrRequestObject struct {
}

type DeleteRVTO2AddrResponseObject interface {
	VisitDeleteRVTO2AddrResponse(w http.ResponseWriter) error
}

type DeleteRVTO2Addr200JSONResponse RVTO2Addr

func (response DeleteRVTO2Addr200JSONResponse) VisitDeleteRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRVTO2Addr401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response DeleteRVTO2Addr401JSONResponse) VisitDeleteRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRVTO2Addr403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response DeleteRVTO2Addr403JSONResponse) VisitDeleteRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRVTO2Addr500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response DeleteRVTO2Addr500JSONResponse) VisitDeleteRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRVTO2AddrRequestObject struct {
}

type GetRVTO2AddrResponseObject interface {
	VisitGetRVTO2AddrResponse(w http.ResponseWriter) error
}

type GetRVTO2Addr200JSONResponse RVTO2Addr

func (response GetRVTO2Addr200JSONResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRVTO2Addr401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response GetRVTO2Addr401JSONResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRVTO2Addr403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response GetRVTO2Addr403JSONResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetRVTO2Addr500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response GetRVTO2Addr500JSONResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRVTO2AddrRequestObject struct {
	Body *UpdateRVTO2AddrJSONRequestBody
}

type UpdateRVTO2AddrResponseObject interface {
	VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error
}

type UpdateRVTO2Addr200JSONResponse RVTO2Addr

func (response UpdateRVTO2Addr200JSONResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRVTO2Addr400JSONResponse struct {
	externalRef0.BadRequestJSONResponse
}

func (response UpdateRVTO2Addr400JSONResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRVTO2Addr401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response UpdateRVTO2Addr401JSONResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRVTO2Addr403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response UpdateRVTO2Addr403JSONResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRVTO2Addr500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response UpdateRVTO2Addr500JSONResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delete the RVTO2 address configuration
	// (DELETE /v1/rvto2addr)
	DeleteRVTO2Addr(ctx context.Context, request DeleteRVTO2AddrRequestObject) (DeleteRVTO2AddrResponseObject, error)
	// Get the current RVTO2 address configuration
	// (GET /v1/rvto2addr)
	GetRVTO2Addr(ctx context.Context, request GetRVTO2AddrRequestObject) (GetRVTO2AddrResponseObject, error)
	// Update the RVTO2 address configuration
	// (PUT /v1/rvto2addr)
	UpdateRVTO2Addr(ctx context.Context, request UpdateRVTO2AddrRequestObject) (UpdateRVTO2AddrResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteRVTO2Addr operation middleware
func (sh *strictHandler) DeleteRVTO2Addr(w http.ResponseWriter, r *http.Request) {
	var request DeleteRVTO2AddrRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRVTO2Addr(ctx, request.(DeleteRVTO2AddrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRVTO2Addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRVTO2AddrResponseObject); ok {
		if err := validResponse.VisitDeleteRVTO2AddrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRVTO2Addr operation middleware
func (sh *strictHandler) GetRVTO2Addr(w http.ResponseWriter, r *http.Request) {
	var request GetRVTO2AddrRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRVTO2Addr(ctx, request.(GetRVTO2AddrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRVTO2Addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRVTO2AddrResponseObject); ok {
		if err := validResponse.VisitGetRVTO2AddrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRVTO2Addr operation middleware
func (sh *strictHandler) UpdateRVTO2Addr(w http.ResponseWriter, r *http.Request) {
	var request UpdateRVTO2AddrRequestObject

	var body UpdateRVTO2AddrJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRVTO2Addr(ctx, request.(UpdateRVTO2AddrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRVTO2Addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRVTO2AddrResponseObject); ok {
		if err := validResponse.VisitUpdateRVTO2AddrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
