//go:build go1.22

// Package ownerinfo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package ownerinfo

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/api/v1/components"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for TransportProtocol.
const (
	Coap  TransportProtocol = "coap"
	Http  TransportProtocol = "http"
	Https TransportProtocol = "https"
	Rest  TransportProtocol = "rest"
	Tcp   TransportProtocol = "tcp"
	Tls   TransportProtocol = "tls"
)

// Valid indicates whether the value is a known member of the TransportProtocol enum.
func (e TransportProtocol) Valid() bool {
	switch e {
	case Coap:
		return true
	case Http:
		return true
	case Https:
		return true
	case Rest:
		return true
	case Tcp:
		return true
	case Tls:
		return true
	default:
		return false
	}
}

// PortString defines model for PortString.
type PortString = string

// RVTO2Addr Rendezvous TO2 address configuration. Specifies one or more owner server
// addresses that devices should use to connect during the TO2 (Transfer of
// Ownership 2) protocol after completing rendezvous. Multiple entries provide
// fallback options if the primary address is unreachable.
type RVTO2Addr = []RVTO2AddrEntry

// RVTO2AddrEntry A single owner server address entry. Each entry specifies the protocol,
// network location (DNS hostname and/or IP address), and port for connecting
// to the owner server during TO2 protocol.
//
// Both 'dns' and 'ip' fields are optional and may be provided independently
// or together. However, at least one addressing method MUST be specified
// (non-null) as required by FDO specification section 3.3.14. Requests that
// omit both 'dns' and 'ip' will be rejected with a 400 Bad Request error.
//
// When both 'dns' and 'ip' are provided, the device MUST attempt to connect
// using the DNS address first. The device MUST only use the IP address after
// all DNS connection attempts have failed. This behavior is defined in the
// FDO specification section 3.3.14.
type RVTO2AddrEntry struct {
	Dns  *externalRef0.DNSHostname `json:"dns,omitempty"`
	Ip   *externalRef0.IPv4Address `json:"ip,omitempty"`
	Port PortString                `json:"port"`

	// Protocol Transport protocol for TO2 owner server connections
	// (FDO specification section 3.3.14, TransportProtocol).
	// - `http` - HTTP protocol (code 3)
	// - `https` - HTTPS protocol (code 5)
	// - `tcp` - Raw TCP connection (code 1)
	// - `tls` - TLS-secured TCP connection (code 2)
	// - `coap` - CoAP over UDP (code 4)
	// - `rest` - RESTful HTTP/HTTPS (mapped to HTTPS)
	Protocol TransportProtocol `json:"protocol"`
}

// TransportProtocol Transport protocol for TO2 owner server connections
// (FDO specification section 3.3.14, TransportProtocol).
// - `http` - HTTP protocol (code 3)
// - `https` - HTTPS protocol (code 5)
// - `tcp` - Raw TCP connection (code 1)
// - `tls` - TLS-secured TCP connection (code 2)
// - `coap` - CoAP over UDP (code 4)
// - `rest` - RESTful HTTP/HTTPS (mapped to HTTPS)
type TransportProtocol string

// CreateRVTO2AddrJSONRequestBody defines body for CreateRVTO2Addr for application/json ContentType.
type CreateRVTO2AddrJSONRequestBody = RVTO2Addr

// UpdateRVTO2AddrJSONRequestBody defines body for UpdateRVTO2Addr for application/json ContentType.
type UpdateRVTO2AddrJSONRequestBody = RVTO2Addr

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the current owner redirect info (RVTO2Addr) configuration (Deprecated)
	// (GET /owner/redirect)
	GetRVTO2Addr(w http.ResponseWriter, r *http.Request)
	// Create the owner redirect info (RVTOAddr) configuration (Deprecated)
	// (POST /owner/redirect)
	CreateRVTO2Addr(w http.ResponseWriter, r *http.Request)
	// Update the owner redirect info (RVTO2Addr) configuration (Deprecated)
	// (PUT /owner/redirect)
	UpdateRVTO2Addr(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetRVTO2Addr operation middleware
func (siw *ServerInterfaceWrapper) GetRVTO2Addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRVTO2Addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRVTO2Addr operation middleware
func (siw *ServerInterfaceWrapper) CreateRVTO2Addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRVTO2Addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRVTO2Addr operation middleware
func (siw *ServerInterfaceWrapper) UpdateRVTO2Addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRVTO2Addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/owner/redirect", wrapper.GetRVTO2Addr)
	m.HandleFunc("POST "+options.BaseURL+"/owner/redirect", wrapper.CreateRVTO2Addr)
	m.HandleFunc("PUT "+options.BaseURL+"/owner/redirect", wrapper.UpdateRVTO2Addr)

	return m
}

type GetRVTO2AddrRequestObject struct {
}

type GetRVTO2AddrResponseObject interface {
	VisitGetRVTO2AddrResponse(w http.ResponseWriter) error
}

type GetRVTO2Addr200JSONResponse RVTO2Addr

func (response GetRVTO2Addr200JSONResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRVTO2Addr404TextResponse externalRef0.ErrorString

func (response GetRVTO2Addr404TextResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type GetRVTO2Addr500TextResponse externalRef0.ErrorString

func (response GetRVTO2Addr500TextResponse) VisitGetRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRVTO2AddrRequestObject struct {
	Body *CreateRVTO2AddrJSONRequestBody
}

type CreateRVTO2AddrResponseObject interface {
	VisitCreateRVTO2AddrResponse(w http.ResponseWriter) error
}

type CreateRVTO2Addr201JSONResponse RVTO2Addr

func (response CreateRVTO2Addr201JSONResponse) VisitCreateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRVTO2Addr400TextResponse externalRef0.ErrorString

func (response CreateRVTO2Addr400TextResponse) VisitCreateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRVTO2Addr409TextResponse externalRef0.ErrorString

func (response CreateRVTO2Addr409TextResponse) VisitCreateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(409)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRVTO2Addr413TextResponse externalRef0.ErrorString

func (response CreateRVTO2Addr413TextResponse) VisitCreateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(413)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRVTO2Addr500TextResponse externalRef0.ErrorString

func (response CreateRVTO2Addr500TextResponse) VisitCreateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRVTO2AddrRequestObject struct {
	Body *UpdateRVTO2AddrJSONRequestBody
}

type UpdateRVTO2AddrResponseObject interface {
	VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error
}

type UpdateRVTO2Addr200JSONResponse RVTO2Addr

func (response UpdateRVTO2Addr200JSONResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRVTO2Addr400TextResponse externalRef0.ErrorString

func (response UpdateRVTO2Addr400TextResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRVTO2Addr404TextResponse externalRef0.ErrorString

func (response UpdateRVTO2Addr404TextResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRVTO2Addr413TextResponse externalRef0.ErrorString

func (response UpdateRVTO2Addr413TextResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(413)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRVTO2Addr500TextResponse externalRef0.ErrorString

func (response UpdateRVTO2Addr500TextResponse) VisitUpdateRVTO2AddrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get the current owner redirect info (RVTO2Addr) configuration (Deprecated)
	// (GET /owner/redirect)
	GetRVTO2Addr(ctx context.Context, request GetRVTO2AddrRequestObject) (GetRVTO2AddrResponseObject, error)
	// Create the owner redirect info (RVTOAddr) configuration (Deprecated)
	// (POST /owner/redirect)
	CreateRVTO2Addr(ctx context.Context, request CreateRVTO2AddrRequestObject) (CreateRVTO2AddrResponseObject, error)
	// Update the owner redirect info (RVTO2Addr) configuration (Deprecated)
	// (PUT /owner/redirect)
	UpdateRVTO2Addr(ctx context.Context, request UpdateRVTO2AddrRequestObject) (UpdateRVTO2AddrResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetRVTO2Addr operation middleware
func (sh *strictHandler) GetRVTO2Addr(w http.ResponseWriter, r *http.Request) {
	var request GetRVTO2AddrRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRVTO2Addr(ctx, request.(GetRVTO2AddrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRVTO2Addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRVTO2AddrResponseObject); ok {
		if err := validResponse.VisitGetRVTO2AddrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRVTO2Addr operation middleware
func (sh *strictHandler) CreateRVTO2Addr(w http.ResponseWriter, r *http.Request) {
	var request CreateRVTO2AddrRequestObject

	var body CreateRVTO2AddrJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRVTO2Addr(ctx, request.(CreateRVTO2AddrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRVTO2Addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRVTO2AddrResponseObject); ok {
		if err := validResponse.VisitCreateRVTO2AddrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRVTO2Addr operation middleware
func (sh *strictHandler) UpdateRVTO2Addr(w http.ResponseWriter, r *http.Request) {
	var request UpdateRVTO2AddrRequestObject

	var body UpdateRVTO2AddrJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRVTO2Addr(ctx, request.(UpdateRVTO2AddrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRVTO2Addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRVTO2AddrResponseObject); ok {
		if err := validResponse.VisitUpdateRVTO2AddrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
