//go:build go1.22

// Package voucher provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package voucher

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BasicAuthScopes  = "BasicAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
	Oauth2AuthScopes = "Oauth2Auth.Scopes"
	OidcAuthScopes   = "OidcAuth.Scopes"
)

// Defines values for HashAlgorithm.
const (
	HMACSHA256 HashAlgorithm = "HMAC-SHA-256"
	HMACSHA384 HashAlgorithm = "HMAC-SHA-384"
	HMACSHA512 HashAlgorithm = "HMAC-SHA-512"
	SHA256     HashAlgorithm = "SHA-256"
	SHA384     HashAlgorithm = "SHA-384"
	SHA512     HashAlgorithm = "SHA-512"
)

// Defines values for PublicKeyType.
const (
	RSA2048RESTR PublicKeyType = "RSA2048RESTR"
	RSAPKCS      PublicKeyType = "RSAPKCS"
	SECP256R1    PublicKeyType = "SECP256R1"
	SECP384R1    PublicKeyType = "SECP384R1"
)

// Defines values for ListOwnershipVouchersParamsSortBy.
const (
	CreatedAt  ListOwnershipVouchersParamsSortBy = "createdAt"
	DeviceInfo ListOwnershipVouchersParamsSortBy = "deviceInfo"
	Guid       ListOwnershipVouchersParamsSortBy = "guid"
	UpdatedAt  ListOwnershipVouchersParamsSortBy = "updatedAt"
)

// Defines values for ListOwnershipVouchersParamsSortOrder.
const (
	Asc  ListOwnershipVouchersParamsSortOrder = "asc"
	Desc ListOwnershipVouchersParamsSortOrder = "desc"
)

// Hash defines model for Hash.
type Hash struct {
	// Algorithm Hash algorithm.
	Algorithm HashAlgorithm `json:"algorithm"`

	// Value Hexadecimal hash value.
	Value string `json:"value"`
}

// HashAlgorithm Hash algorithm.
type HashAlgorithm string

// OwnershipVoucher defines model for OwnershipVoucher.
type OwnershipVoucher struct {
	// CertChain X.509 certificate chain in PEM format (null for Intel EPID).
	CertChain *[]string `json:"certChain"`

	// DeviceInfo Device information string.
	DeviceInfo VoucherDeviceInfo `json:"deviceInfo"`

	// Entries Ownership entry chain.
	Entries []VoucherEntry `json:"entries"`

	// Guid The device GUID (32 hexadecimal characters).
	Guid   VoucherGuid   `json:"guid"`
	Header VoucherHeader `json:"header"`
	Hmac   Hash          `json:"hmac"`

	// NumEntries Number of ownership entries in the voucher.
	NumEntries VoucherNumEntries `json:"numEntries"`

	// ProtocolVersion The FDO protocol version (e.g., 101 for version 1.1).
	ProtocolVersion VoucherProtocolVersion `json:"protocolVersion"`
}

// OwnershipVoucherCreatedAt The timestamp when the voucher was created.
type OwnershipVoucherCreatedAt = time.Time

// OwnershipVoucherInfo defines model for OwnershipVoucherInfo.
type OwnershipVoucherInfo struct {
	// CreatedAt The timestamp when the voucher was created.
	CreatedAt OwnershipVoucherCreatedAt `json:"createdAt"`

	// UpdatedAt The timestamp when the voucher was last updated.
	UpdatedAt OwnershipVoucherUpdatedAt `json:"updatedAt"`
	Voucher   OwnershipVoucher          `json:"voucher"`
}

// OwnershipVoucherSummary defines model for OwnershipVoucherSummary.
type OwnershipVoucherSummary struct {
	// DeviceInfo Device information string.
	DeviceInfo VoucherDeviceInfo `json:"deviceInfo"`

	// Guid The device GUID (32 hexadecimal characters).
	Guid VoucherGuid `json:"guid"`

	// NumEntries Number of ownership entries in the voucher.
	NumEntries VoucherNumEntries `json:"numEntries"`

	// ProtocolVersion The FDO protocol version (e.g., 101 for version 1.1).
	ProtocolVersion VoucherProtocolVersion `json:"protocolVersion"`
}

// OwnershipVoucherSummaryInfo defines model for OwnershipVoucherSummaryInfo.
type OwnershipVoucherSummaryInfo struct {
	// CreatedAt The timestamp when the voucher was created.
	CreatedAt OwnershipVoucherCreatedAt `json:"createdAt"`

	// UpdatedAt The timestamp when the voucher was last updated.
	UpdatedAt OwnershipVoucherUpdatedAt `json:"updatedAt"`
	Voucher   OwnershipVoucherSummary   `json:"voucher"`
}

// OwnershipVoucherUpdatedAt The timestamp when the voucher was last updated.
type OwnershipVoucherUpdatedAt = time.Time

// OwnershipVouchersPaginated defines model for OwnershipVouchersPaginated.
type OwnershipVouchersPaginated struct {
	// Limit The number of items returned in this response.
	Limit int `json:"limit"`

	// Offset The offset from the beginning of the collection.
	Offset int `json:"offset"`

	// Total Total number of ownership vouchers available.
	Total    int                           `json:"total"`
	Vouchers []OwnershipVoucherSummaryInfo `json:"vouchers"`
}

// PublicKey defines model for PublicKey.
type PublicKey struct {
	// Type Public key algorithm type.
	Type PublicKeyType `json:"type"`

	// Value Base64-encoded public key.
	Value string `json:"value"`
}

// PublicKeyType Public key algorithm type.
type PublicKeyType string

// VoucherDeviceInfo Device information string.
type VoucherDeviceInfo = string

// VoucherEntry defines model for VoucherEntry.
type VoucherEntry struct {
	// Extra Additional optional data.
	Extra        *map[string]interface{} `json:"extra"`
	HeaderHash   Hash                    `json:"headerHash"`
	PreviousHash Hash                    `json:"previousHash"`
	PublicKey    PublicKey               `json:"publicKey"`
}

// VoucherGuid The device GUID (32 hexadecimal characters).
type VoucherGuid = string

// VoucherHeader defines model for VoucherHeader.
type VoucherHeader struct {
	// CertChainHash Hash of the certificate chain (required when certChain is present).
	CertChainHash *Hash `json:"certChainHash"`

	// DeviceInfo Device information string.
	DeviceInfo string `json:"deviceInfo"`

	// Guid The device GUID (32 hexadecimal characters).
	Guid            string    `json:"guid"`
	ManufacturerKey PublicKey `json:"manufacturerKey"`

	// RvInfo Rendezvous information array containing one or more instruction sets.
	// Each instruction set guides devices on how to connect to the rendezvous server,
	// including network configuration, protocols, and connection parameters.
	// Multiple instruction sets provide fallback options for device connectivity.
	RvInfo externalRef0.RVInfo `json:"rvInfo"`

	// Version Header version.
	Version int `json:"version"`
}

// VoucherNumEntries Number of ownership entries in the voucher.
type VoucherNumEntries = int

// VoucherProtocolVersion The FDO protocol version (e.g., 101 for version 1.1).
type VoucherProtocolVersion = int

// ListOwnershipVouchersParams defines parameters for ListOwnershipVouchers.
type ListOwnershipVouchersParams struct {
	// Limit The number of items to return per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Guid Filters the results by the exact device GUID.
	Guid *string `form:"guid,omitempty" json:"guid,omitempty"`

	// DeviceInfo Filters the results by device information (case-insensitive partial match).
	DeviceInfo *string `form:"deviceInfo,omitempty" json:"deviceInfo,omitempty"`

	// Search Searches within device info and GUID fields (case-insensitive).
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sorts the results by the specified field.
	SortBy *ListOwnershipVouchersParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Specifies the sorting order.
	SortOrder *ListOwnershipVouchersParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListOwnershipVouchersParamsSortBy defines parameters for ListOwnershipVouchers.
type ListOwnershipVouchersParamsSortBy string

// ListOwnershipVouchersParamsSortOrder defines parameters for ListOwnershipVouchers.
type ListOwnershipVouchersParamsSortOrder string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all ownership vouchers
	// (GET /vouchers)
	ListOwnershipVouchers(w http.ResponseWriter, r *http.Request, params ListOwnershipVouchersParams)
	// Import ownership voucher(s)
	// (POST /vouchers)
	ImportOwnershipVouchers(w http.ResponseWriter, r *http.Request)
	// Delete an ownership voucher by GUID
	// (DELETE /vouchers/{guid})
	DeleteOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string)
	// Get an ownership voucher by GUID
	// (GET /vouchers/{guid})
	GetOwnershipVoucherByGuid(w http.ResponseWriter, r *http.Request, guid string)
	// Extend an ownership voucher
	// (POST /vouchers/{guid}/extend)
	ExtendOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOwnershipVouchers operation middleware
func (siw *ServerInterfaceWrapper) ListOwnershipVouchers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOwnershipVouchersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "guid" -------------

	err = runtime.BindQueryParameter("form", true, false, "guid", r.URL.Query(), &params.Guid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	// ------------- Optional query parameter "deviceInfo" -------------

	err = runtime.BindQueryParameter("form", true, false, "deviceInfo", r.URL.Query(), &params.DeviceInfo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceInfo", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", r.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortOrder", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOwnershipVouchers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportOwnershipVouchers operation middleware
func (siw *ServerInterfaceWrapper) ImportOwnershipVouchers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportOwnershipVouchers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOwnershipVoucher operation middleware
func (siw *ServerInterfaceWrapper) DeleteOwnershipVoucher(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOwnershipVoucher(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOwnershipVoucherByGuid operation middleware
func (siw *ServerInterfaceWrapper) GetOwnershipVoucherByGuid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOwnershipVoucherByGuid(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExtendOwnershipVoucher operation middleware
func (siw *ServerInterfaceWrapper) ExtendOwnershipVoucher(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExtendOwnershipVoucher(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/vouchers", wrapper.ListOwnershipVouchers)
	m.HandleFunc("POST "+options.BaseURL+"/vouchers", wrapper.ImportOwnershipVouchers)
	m.HandleFunc("DELETE "+options.BaseURL+"/vouchers/{guid}", wrapper.DeleteOwnershipVoucher)
	m.HandleFunc("GET "+options.BaseURL+"/vouchers/{guid}", wrapper.GetOwnershipVoucherByGuid)
	m.HandleFunc("POST "+options.BaseURL+"/vouchers/{guid}/extend", wrapper.ExtendOwnershipVoucher)

	return m
}

type ListOwnershipVouchersRequestObject struct {
	Params ListOwnershipVouchersParams
}

type ListOwnershipVouchersResponseObject interface {
	VisitListOwnershipVouchersResponse(w http.ResponseWriter) error
}

type ListOwnershipVouchers200JSONResponse OwnershipVouchersPaginated

func (response ListOwnershipVouchers200JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOwnershipVouchers200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ListOwnershipVouchers200ApplicationxPemFileResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ListOwnershipVouchers400JSONResponse struct{ externalRef0.BadRequest }

func (response ListOwnershipVouchers400JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListOwnershipVouchers401JSONResponse struct{ externalRef0.Unauthorized }

func (response ListOwnershipVouchers401JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListOwnershipVouchers403JSONResponse struct{ externalRef0.Forbidden }

func (response ListOwnershipVouchers403JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListOwnershipVouchers500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response ListOwnershipVouchers500JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportOwnershipVouchersRequestObject struct {
	Body io.Reader
}

type ImportOwnershipVouchersResponseObject interface {
	VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error
}

type ImportOwnershipVouchers201JSONResponse struct {
	union json.RawMessage
}

func (response ImportOwnershipVouchers201JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.union)
}

type ImportOwnershipVouchers400JSONResponse struct{ externalRef0.BadRequest }

func (response ImportOwnershipVouchers400JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportOwnershipVouchers401JSONResponse struct{ externalRef0.Unauthorized }

func (response ImportOwnershipVouchers401JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ImportOwnershipVouchers403JSONResponse struct{ externalRef0.Forbidden }

func (response ImportOwnershipVouchers403JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ImportOwnershipVouchers409JSONResponse externalRef0.Error

func (response ImportOwnershipVouchers409JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ImportOwnershipVouchers500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response ImportOwnershipVouchers500JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOwnershipVoucherRequestObject struct {
	Guid string `json:"guid"`
}

type DeleteOwnershipVoucherResponseObject interface {
	VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error
}

type DeleteOwnershipVoucher204Response struct {
}

func (response DeleteOwnershipVoucher204Response) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOwnershipVoucher401JSONResponse struct{ externalRef0.Unauthorized }

func (response DeleteOwnershipVoucher401JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOwnershipVoucher403JSONResponse struct{ externalRef0.Forbidden }

func (response DeleteOwnershipVoucher403JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOwnershipVoucher404JSONResponse struct{ externalRef0.NotFound }

func (response DeleteOwnershipVoucher404JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOwnershipVoucher500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response DeleteOwnershipVoucher500JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetOwnershipVoucherByGuidRequestObject struct {
	Guid string `json:"guid"`
}

type GetOwnershipVoucherByGuidResponseObject interface {
	VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error
}

type GetOwnershipVoucherByGuid200JSONResponse OwnershipVoucher

func (response GetOwnershipVoucherByGuid200JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOwnershipVoucherByGuid200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOwnershipVoucherByGuid200ApplicationxPemFileResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetOwnershipVoucherByGuid401JSONResponse struct{ externalRef0.Unauthorized }

func (response GetOwnershipVoucherByGuid401JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOwnershipVoucherByGuid403JSONResponse struct{ externalRef0.Forbidden }

func (response GetOwnershipVoucherByGuid403JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOwnershipVoucherByGuid404JSONResponse struct{ externalRef0.NotFound }

func (response GetOwnershipVoucherByGuid404JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOwnershipVoucherByGuid500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response GetOwnershipVoucherByGuid500JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExtendOwnershipVoucherRequestObject struct {
	Guid string `json:"guid"`
	Body io.Reader
}

type ExtendOwnershipVoucherResponseObject interface {
	VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error
}

type ExtendOwnershipVoucher200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExtendOwnershipVoucher200ApplicationxPemFileResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExtendOwnershipVoucher400JSONResponse struct{ externalRef0.BadRequest }

func (response ExtendOwnershipVoucher400JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ExtendOwnershipVoucher401JSONResponse struct{ externalRef0.Unauthorized }

func (response ExtendOwnershipVoucher401JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ExtendOwnershipVoucher403JSONResponse struct{ externalRef0.Forbidden }

func (response ExtendOwnershipVoucher403JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ExtendOwnershipVoucher404JSONResponse struct{ externalRef0.NotFound }

func (response ExtendOwnershipVoucher404JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExtendOwnershipVoucher500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response ExtendOwnershipVoucher500JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all ownership vouchers
	// (GET /vouchers)
	ListOwnershipVouchers(ctx context.Context, request ListOwnershipVouchersRequestObject) (ListOwnershipVouchersResponseObject, error)
	// Import ownership voucher(s)
	// (POST /vouchers)
	ImportOwnershipVouchers(ctx context.Context, request ImportOwnershipVouchersRequestObject) (ImportOwnershipVouchersResponseObject, error)
	// Delete an ownership voucher by GUID
	// (DELETE /vouchers/{guid})
	DeleteOwnershipVoucher(ctx context.Context, request DeleteOwnershipVoucherRequestObject) (DeleteOwnershipVoucherResponseObject, error)
	// Get an ownership voucher by GUID
	// (GET /vouchers/{guid})
	GetOwnershipVoucherByGuid(ctx context.Context, request GetOwnershipVoucherByGuidRequestObject) (GetOwnershipVoucherByGuidResponseObject, error)
	// Extend an ownership voucher
	// (POST /vouchers/{guid}/extend)
	ExtendOwnershipVoucher(ctx context.Context, request ExtendOwnershipVoucherRequestObject) (ExtendOwnershipVoucherResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListOwnershipVouchers operation middleware
func (sh *strictHandler) ListOwnershipVouchers(w http.ResponseWriter, r *http.Request, params ListOwnershipVouchersParams) {
	var request ListOwnershipVouchersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOwnershipVouchers(ctx, request.(ListOwnershipVouchersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOwnershipVouchers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOwnershipVouchersResponseObject); ok {
		if err := validResponse.VisitListOwnershipVouchersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportOwnershipVouchers operation middleware
func (sh *strictHandler) ImportOwnershipVouchers(w http.ResponseWriter, r *http.Request) {
	var request ImportOwnershipVouchersRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportOwnershipVouchers(ctx, request.(ImportOwnershipVouchersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportOwnershipVouchers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportOwnershipVouchersResponseObject); ok {
		if err := validResponse.VisitImportOwnershipVouchersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOwnershipVoucher operation middleware
func (sh *strictHandler) DeleteOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string) {
	var request DeleteOwnershipVoucherRequestObject

	request.Guid = guid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOwnershipVoucher(ctx, request.(DeleteOwnershipVoucherRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOwnershipVoucher")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOwnershipVoucherResponseObject); ok {
		if err := validResponse.VisitDeleteOwnershipVoucherResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOwnershipVoucherByGuid operation middleware
func (sh *strictHandler) GetOwnershipVoucherByGuid(w http.ResponseWriter, r *http.Request, guid string) {
	var request GetOwnershipVoucherByGuidRequestObject

	request.Guid = guid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOwnershipVoucherByGuid(ctx, request.(GetOwnershipVoucherByGuidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOwnershipVoucherByGuid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOwnershipVoucherByGuidResponseObject); ok {
		if err := validResponse.VisitGetOwnershipVoucherByGuidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExtendOwnershipVoucher operation middleware
func (sh *strictHandler) ExtendOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string) {
	var request ExtendOwnershipVoucherRequestObject

	request.Guid = guid

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExtendOwnershipVoucher(ctx, request.(ExtendOwnershipVoucherRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExtendOwnershipVoucher")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExtendOwnershipVoucherResponseObject); ok {
		if err := validResponse.VisitExtendOwnershipVoucherResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
