// Package components provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package components

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for MediumMedium.
const (
	Wifi1    MediumMedium = "wifi_1"
	Wifi2    MediumMedium = "wifi_2"
	Wifi3    MediumMedium = "wifi_3"
	Wifi4    MediumMedium = "wifi_4"
	Wifi5    MediumMedium = "wifi_5"
	Wifi6    MediumMedium = "wifi_6"
	Wifi7    MediumMedium = "wifi_7"
	Wifi8    MediumMedium = "wifi_8"
	Wifi9    MediumMedium = "wifi_9"
	WifiAll  MediumMedium = "wifi_all"
	Wired1   MediumMedium = "wired_1"
	Wired2   MediumMedium = "wired_2"
	Wired3   MediumMedium = "wired_3"
	Wired4   MediumMedium = "wired_4"
	Wired5   MediumMedium = "wired_5"
	Wired6   MediumMedium = "wired_6"
	Wired7   MediumMedium = "wired_7"
	Wired8   MediumMedium = "wired_8"
	Wired9   MediumMedium = "wired_9"
	WiredAll MediumMedium = "wired_all"
)

// Defines values for ProtocolType.
const (
	Coap    ProtocolType = "coap"
	CoapTcp ProtocolType = "coap+tcp"
	Http    ProtocolType = "http"
	Https   ProtocolType = "https"
	Rest    ProtocolType = "rest"
	Tcp     ProtocolType = "tcp"
	Tls     ProtocolType = "tls"
)

// ClCertHash Client certificate hash for validation (SHA-256 or SHA-384)
type ClCertHash struct {
	ClCertHash *string `json:"cl_cert_hash,omitempty"`
}

// DNS DNS hostname for the server
type DNS struct {
	Dns *DNSHostname `json:"dns,omitempty"`
}

// DNSHostname defines model for DNSHostname.
type DNSHostname = string

// DelaySeconds Delay in seconds before attempting connection
type DelaySeconds struct {
	DelaySeconds *uint32 `json:"delay_seconds,omitempty"`
}

// DevOnly Instruction applies to device only (not owner)
type DevOnly struct {
	DevOnly *bool `json:"dev_only,omitempty"`
}

// DevicePort Port number on the device side
type DevicePort struct {
	DevicePort *PortNumber `json:"device_port,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

// ExtRV Extended rendezvous information
type ExtRV struct {
	ExtRv *string `json:"ext_rv,omitempty"`
}

// IP IPv4 address for the server
type IP struct {
	Ip *IPv4Address `json:"ip,omitempty"`
}

// IPv4Address defines model for IPv4Address.
type IPv4Address = string

// Medium Network medium/interface to use for communication:
// - `wired_1` through `wired_9` - Specific wired network interfaces
// - `wifi_1` through `wifi_9` - Specific WiFi network interfaces
// - `wired_all` - Any available wired interface
// - `wifi_all` - Any available WiFi interface
type Medium struct {
	Medium *MediumMedium `json:"medium,omitempty"`
}

// MediumMedium defines model for Medium.Medium.
type MediumMedium string

// OwnerOnly Instruction applies to owner only (not device)
type OwnerOnly struct {
	OwnerOnly *bool `json:"owner_only,omitempty"`
}

// OwnerPort Port number on the owner/server side
type OwnerPort struct {
	OwnerPort *PortNumber `json:"owner_port,omitempty"`
}

// PortNumber defines model for PortNumber.
type PortNumber = int

// Protocol Communication protocol specification
type Protocol struct {
	// Protocol Protocol to use for communication:
	// - `rest` - RESTful HTTP/HTTPS
	// - `http` - HTTP protocol
	// - `https` - HTTPS protocol (recommended for production)
	// - `tcp` - Raw TCP connection
	// - `tls` - TLS-secured TCP connection
	// - `coap+tcp` - CoAP over TCP
	// - `coap` - Constrained Application Protocol
	Protocol *ProtocolType `json:"protocol,omitempty"`
}

// ProtocolType Protocol to use for communication:
// - `rest` - RESTful HTTP/HTTPS
// - `http` - HTTP protocol
// - `https` - HTTPS protocol (recommended for production)
// - `tcp` - Raw TCP connection
// - `tls` - TLS-secured TCP connection
// - `coap+tcp` - CoAP over TCP
// - `coap` - Constrained Application Protocol
type ProtocolType string

// RVBypass Bypass rendezvous server and connect directly to owner
type RVBypass struct {
	RvBypass *bool `json:"rv_bypass,omitempty"`
}

// RVInfo Rendezvous information array containing one or more instruction sets.
// Each instruction set guides devices on how to connect to the rendezvous server,
// including network configuration, protocols, and connection parameters.
// Multiple instruction sets provide fallback options for device connectivity.
type RVInfo = []RVInstruction

// RVInstruction defines model for RVInstruction.
type RVInstruction = []RVInstruction_Item

// RVInstruction_Item defines model for RVInstruction.Item.
type RVInstruction_Item struct {
	union json.RawMessage
}

// SvCertHash Server certificate hash for validation (SHA-256 or SHA-384)
type SvCertHash struct {
	SvCertHash *string `json:"sv_cert_hash,omitempty"`
}

// UserInput Requires user input during rendezvous
type UserInput struct {
	UserInput *string `json:"user_input,omitempty"`
}

// WifiPW WiFi network password
type WifiPW struct {
	WifiPw *string `json:"wifi_pw,omitempty"`
}

// WifiSSID WiFi network SSID (Service Set Identifier)
type WifiSSID struct {
	WifiSsid *string `json:"wifi_ssid,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// AsDNS returns the union data inside the RVInstruction_Item as a DNS
func (t RVInstruction_Item) AsDNS() (DNS, error) {
	var body DNS
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDNS overwrites any union data inside the RVInstruction_Item as the provided DNS
func (t *RVInstruction_Item) FromDNS(v DNS) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDNS performs a merge with any union data inside the RVInstruction_Item, using the provided DNS
func (t *RVInstruction_Item) MergeDNS(v DNS) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIP returns the union data inside the RVInstruction_Item as a IP
func (t RVInstruction_Item) AsIP() (IP, error) {
	var body IP
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIP overwrites any union data inside the RVInstruction_Item as the provided IP
func (t *RVInstruction_Item) FromIP(v IP) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIP performs a merge with any union data inside the RVInstruction_Item, using the provided IP
func (t *RVInstruction_Item) MergeIP(v IP) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProtocol returns the union data inside the RVInstruction_Item as a Protocol
func (t RVInstruction_Item) AsProtocol() (Protocol, error) {
	var body Protocol
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProtocol overwrites any union data inside the RVInstruction_Item as the provided Protocol
func (t *RVInstruction_Item) FromProtocol(v Protocol) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProtocol performs a merge with any union data inside the RVInstruction_Item, using the provided Protocol
func (t *RVInstruction_Item) MergeProtocol(v Protocol) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMedium returns the union data inside the RVInstruction_Item as a Medium
func (t RVInstruction_Item) AsMedium() (Medium, error) {
	var body Medium
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMedium overwrites any union data inside the RVInstruction_Item as the provided Medium
func (t *RVInstruction_Item) FromMedium(v Medium) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMedium performs a merge with any union data inside the RVInstruction_Item, using the provided Medium
func (t *RVInstruction_Item) MergeMedium(v Medium) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDevicePort returns the union data inside the RVInstruction_Item as a DevicePort
func (t RVInstruction_Item) AsDevicePort() (DevicePort, error) {
	var body DevicePort
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDevicePort overwrites any union data inside the RVInstruction_Item as the provided DevicePort
func (t *RVInstruction_Item) FromDevicePort(v DevicePort) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDevicePort performs a merge with any union data inside the RVInstruction_Item, using the provided DevicePort
func (t *RVInstruction_Item) MergeDevicePort(v DevicePort) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOwnerPort returns the union data inside the RVInstruction_Item as a OwnerPort
func (t RVInstruction_Item) AsOwnerPort() (OwnerPort, error) {
	var body OwnerPort
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwnerPort overwrites any union data inside the RVInstruction_Item as the provided OwnerPort
func (t *RVInstruction_Item) FromOwnerPort(v OwnerPort) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwnerPort performs a merge with any union data inside the RVInstruction_Item, using the provided OwnerPort
func (t *RVInstruction_Item) MergeOwnerPort(v OwnerPort) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWifiSSID returns the union data inside the RVInstruction_Item as a WifiSSID
func (t RVInstruction_Item) AsWifiSSID() (WifiSSID, error) {
	var body WifiSSID
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWifiSSID overwrites any union data inside the RVInstruction_Item as the provided WifiSSID
func (t *RVInstruction_Item) FromWifiSSID(v WifiSSID) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWifiSSID performs a merge with any union data inside the RVInstruction_Item, using the provided WifiSSID
func (t *RVInstruction_Item) MergeWifiSSID(v WifiSSID) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWifiPW returns the union data inside the RVInstruction_Item as a WifiPW
func (t RVInstruction_Item) AsWifiPW() (WifiPW, error) {
	var body WifiPW
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWifiPW overwrites any union data inside the RVInstruction_Item as the provided WifiPW
func (t *RVInstruction_Item) FromWifiPW(v WifiPW) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWifiPW performs a merge with any union data inside the RVInstruction_Item, using the provided WifiPW
func (t *RVInstruction_Item) MergeWifiPW(v WifiPW) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDevOnly returns the union data inside the RVInstruction_Item as a DevOnly
func (t RVInstruction_Item) AsDevOnly() (DevOnly, error) {
	var body DevOnly
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDevOnly overwrites any union data inside the RVInstruction_Item as the provided DevOnly
func (t *RVInstruction_Item) FromDevOnly(v DevOnly) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDevOnly performs a merge with any union data inside the RVInstruction_Item, using the provided DevOnly
func (t *RVInstruction_Item) MergeDevOnly(v DevOnly) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOwnerOnly returns the union data inside the RVInstruction_Item as a OwnerOnly
func (t RVInstruction_Item) AsOwnerOnly() (OwnerOnly, error) {
	var body OwnerOnly
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwnerOnly overwrites any union data inside the RVInstruction_Item as the provided OwnerOnly
func (t *RVInstruction_Item) FromOwnerOnly(v OwnerOnly) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwnerOnly performs a merge with any union data inside the RVInstruction_Item, using the provided OwnerOnly
func (t *RVInstruction_Item) MergeOwnerOnly(v OwnerOnly) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRVBypass returns the union data inside the RVInstruction_Item as a RVBypass
func (t RVInstruction_Item) AsRVBypass() (RVBypass, error) {
	var body RVBypass
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRVBypass overwrites any union data inside the RVInstruction_Item as the provided RVBypass
func (t *RVInstruction_Item) FromRVBypass(v RVBypass) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRVBypass performs a merge with any union data inside the RVInstruction_Item, using the provided RVBypass
func (t *RVInstruction_Item) MergeRVBypass(v RVBypass) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDelaySeconds returns the union data inside the RVInstruction_Item as a DelaySeconds
func (t RVInstruction_Item) AsDelaySeconds() (DelaySeconds, error) {
	var body DelaySeconds
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDelaySeconds overwrites any union data inside the RVInstruction_Item as the provided DelaySeconds
func (t *RVInstruction_Item) FromDelaySeconds(v DelaySeconds) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDelaySeconds performs a merge with any union data inside the RVInstruction_Item, using the provided DelaySeconds
func (t *RVInstruction_Item) MergeDelaySeconds(v DelaySeconds) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSvCertHash returns the union data inside the RVInstruction_Item as a SvCertHash
func (t RVInstruction_Item) AsSvCertHash() (SvCertHash, error) {
	var body SvCertHash
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSvCertHash overwrites any union data inside the RVInstruction_Item as the provided SvCertHash
func (t *RVInstruction_Item) FromSvCertHash(v SvCertHash) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSvCertHash performs a merge with any union data inside the RVInstruction_Item, using the provided SvCertHash
func (t *RVInstruction_Item) MergeSvCertHash(v SvCertHash) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClCertHash returns the union data inside the RVInstruction_Item as a ClCertHash
func (t RVInstruction_Item) AsClCertHash() (ClCertHash, error) {
	var body ClCertHash
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClCertHash overwrites any union data inside the RVInstruction_Item as the provided ClCertHash
func (t *RVInstruction_Item) FromClCertHash(v ClCertHash) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClCertHash performs a merge with any union data inside the RVInstruction_Item, using the provided ClCertHash
func (t *RVInstruction_Item) MergeClCertHash(v ClCertHash) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserInput returns the union data inside the RVInstruction_Item as a UserInput
func (t RVInstruction_Item) AsUserInput() (UserInput, error) {
	var body UserInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserInput overwrites any union data inside the RVInstruction_Item as the provided UserInput
func (t *RVInstruction_Item) FromUserInput(v UserInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserInput performs a merge with any union data inside the RVInstruction_Item, using the provided UserInput
func (t *RVInstruction_Item) MergeUserInput(v UserInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExtRV returns the union data inside the RVInstruction_Item as a ExtRV
func (t RVInstruction_Item) AsExtRV() (ExtRV, error) {
	var body ExtRV
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExtRV overwrites any union data inside the RVInstruction_Item as the provided ExtRV
func (t *RVInstruction_Item) FromExtRV(v ExtRV) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExtRV performs a merge with any union data inside the RVInstruction_Item, using the provided ExtRV
func (t *RVInstruction_Item) MergeExtRV(v ExtRV) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RVInstruction_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RVInstruction_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
