//go:build go1.22

// Package deviceca provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package deviceca

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BasicAuthScopes  = "BasicAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
	Oauth2AuthScopes = "Oauth2Auth.Scopes"
	OidcAuthScopes   = "OidcAuth.Scopes"
)

// Defines values for ListTrustedDeviceCACertsParamsValidityStatus.
const (
	Expired     ListTrustedDeviceCACertsParamsValidityStatus = "expired"
	NotYetValid ListTrustedDeviceCACertsParamsValidityStatus = "not-yet-valid"
	Valid       ListTrustedDeviceCACertsParamsValidityStatus = "valid"
)

// Defines values for ListTrustedDeviceCACertsParamsSortBy.
const (
	CreatedAt ListTrustedDeviceCACertsParamsSortBy = "createdAt"
	Issuer    ListTrustedDeviceCACertsParamsSortBy = "issuer"
	NotAfter  ListTrustedDeviceCACertsParamsSortBy = "notAfter"
	NotBefore ListTrustedDeviceCACertsParamsSortBy = "notBefore"
	Subject   ListTrustedDeviceCACertsParamsSortBy = "subject"
)

// Defines values for ListTrustedDeviceCACertsParamsSortOrder.
const (
	Asc  ListTrustedDeviceCACertsParamsSortOrder = "asc"
	Desc ListTrustedDeviceCACertsParamsSortOrder = "desc"
)

// TrustedDeviceCACert defines model for TrustedDeviceCACert.
type TrustedDeviceCACert struct {
	// CreatedAt The timestamp when the certificate was added.
	CreatedAt time.Time `json:"createdAt"`

	// Fingerprint The SHA-256 fingerprint of the certificate (64 hexadecimal characters).
	Fingerprint string `json:"fingerprint"`

	// Issuer The issuer distinguished name of the certificate.
	Issuer string `json:"issuer"`

	// NotAfter The end date of the certificate's validity period.
	NotAfter time.Time `json:"notAfter"`

	// NotBefore The start date of the certificate's validity period.
	NotBefore time.Time `json:"notBefore"`

	// Pem The full certificate content in PEM format.
	Pem string `json:"pem"`

	// Subject The subject distinguished name of the certificate.
	Subject string `json:"subject"`
}

// TrustedDeviceCACerts defines model for TrustedDeviceCACerts.
type TrustedDeviceCACerts = []TrustedDeviceCACert

// TrustedDeviceCACertsImportResult defines model for TrustedDeviceCACertsImportResult.
type TrustedDeviceCACertsImportResult struct {
	// Certs Array of certificates that were successfully imported (does not include malformed, expired or already existing certificates).
	Certs []TrustedDeviceCACert `json:"certs"`

	// Detected Total number of certificate blocks found in the PEM data.
	Detected int `json:"detected"`

	// Imported Number of certificates successfully added to the database.
	Imported int `json:"imported"`

	// Malformed Number of certificate blocks that could not be parsed or validated.
	Malformed int `json:"malformed"`

	// Messages Detailed import result messages for each certificate found in the PEM data.
	Messages []string `json:"messages"`

	// Skipped Number of certificates that were skipped (includes malformed, expired, and already existing certificates).
	Skipped int `json:"skipped"`
}

// TrustedDeviceCACertsPaginated defines model for TrustedDeviceCACertsPaginated.
type TrustedDeviceCACertsPaginated struct {
	Certs TrustedDeviceCACerts `json:"certs"`

	// Limit The number of items returned in this response.
	Limit int `json:"limit"`

	// Offset The offset from the beginning of the collection.
	Offset int `json:"offset"`

	// Total Total number of trusted device CA certificates available.
	Total int `json:"total"`
}

// ListTrustedDeviceCACertsParams defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParams struct {
	// Limit The number of items to return per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Issuer Filters the results by the exact issuer distinguished name.
	Issuer *string `form:"issuer,omitempty" json:"issuer,omitempty"`

	// Subject Filters the results by the exact subject distinguished name.
	Subject *string `form:"subject,omitempty" json:"subject,omitempty"`

	// ValidityStatus Filters certificates by their validity status.
	ValidityStatus *ListTrustedDeviceCACertsParamsValidityStatus `form:"validityStatus,omitempty" json:"validityStatus,omitempty"`

	// Search Searches within subject and issuer fields (case-insensitive).
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sorts the results by the specified field.
	SortBy *ListTrustedDeviceCACertsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Specifies the sorting order.
	SortOrder *ListTrustedDeviceCACertsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListTrustedDeviceCACertsParamsValidityStatus defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParamsValidityStatus string

// ListTrustedDeviceCACertsParamsSortBy defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParamsSortBy string

// ListTrustedDeviceCACertsParamsSortOrder defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParamsSortOrder string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all trusted device CA certificates
	// (GET /device-ca)
	ListTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request, params ListTrustedDeviceCACertsParams)
	// Import one or more trusted device CA certificates
	// (POST /device-ca)
	ImportTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request)
	// Delete a trusted device CA certificate by fingerprint
	// (DELETE /device-ca/{fingerprint})
	DeleteTrustedDeviceCACert(w http.ResponseWriter, r *http.Request, fingerprint string)
	// Get a trusted device CA certificate by fingerprint
	// (GET /device-ca/{fingerprint})
	GetTrustedDeviceCACertByFingerprint(w http.ResponseWriter, r *http.Request, fingerprint string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTrustedDeviceCACerts operation middleware
func (siw *ServerInterfaceWrapper) ListTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTrustedDeviceCACertsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "issuer" -------------

	err = runtime.BindQueryParameter("form", true, false, "issuer", r.URL.Query(), &params.Issuer)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "issuer", Err: err})
		return
	}

	// ------------- Optional query parameter "subject" -------------

	err = runtime.BindQueryParameter("form", true, false, "subject", r.URL.Query(), &params.Subject)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		return
	}

	// ------------- Optional query parameter "validityStatus" -------------

	err = runtime.BindQueryParameter("form", true, false, "validityStatus", r.URL.Query(), &params.ValidityStatus)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "validityStatus", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", r.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortOrder", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrustedDeviceCACerts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportTrustedDeviceCACerts operation middleware
func (siw *ServerInterfaceWrapper) ImportTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportTrustedDeviceCACerts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrustedDeviceCACert operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrustedDeviceCACert(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fingerprint" -------------
	var fingerprint string

	err = runtime.BindStyledParameterWithOptions("simple", "fingerprint", r.PathValue("fingerprint"), &fingerprint, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fingerprint", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrustedDeviceCACert(w, r, fingerprint)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrustedDeviceCACertByFingerprint operation middleware
func (siw *ServerInterfaceWrapper) GetTrustedDeviceCACertByFingerprint(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fingerprint" -------------
	var fingerprint string

	err = runtime.BindStyledParameterWithOptions("simple", "fingerprint", r.PathValue("fingerprint"), &fingerprint, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fingerprint", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrustedDeviceCACertByFingerprint(w, r, fingerprint)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/device-ca", wrapper.ListTrustedDeviceCACerts)
	m.HandleFunc("POST "+options.BaseURL+"/device-ca", wrapper.ImportTrustedDeviceCACerts)
	m.HandleFunc("DELETE "+options.BaseURL+"/device-ca/{fingerprint}", wrapper.DeleteTrustedDeviceCACert)
	m.HandleFunc("GET "+options.BaseURL+"/device-ca/{fingerprint}", wrapper.GetTrustedDeviceCACertByFingerprint)

	return m
}

type ListTrustedDeviceCACertsRequestObject struct {
	Params ListTrustedDeviceCACertsParams
}

type ListTrustedDeviceCACertsResponseObject interface {
	VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error
}

type ListTrustedDeviceCACerts200JSONResponse TrustedDeviceCACertsPaginated

func (response ListTrustedDeviceCACerts200JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ListTrustedDeviceCACerts200ApplicationxPemFileResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ListTrustedDeviceCACerts400JSONResponse struct{ externalRef0.BadRequest }

func (response ListTrustedDeviceCACerts400JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts401JSONResponse struct{ externalRef0.Unauthorized }

func (response ListTrustedDeviceCACerts401JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts403JSONResponse struct{ externalRef0.Forbidden }

func (response ListTrustedDeviceCACerts403JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response ListTrustedDeviceCACerts500JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportTrustedDeviceCACertsRequestObject struct {
	Body io.Reader
}

type ImportTrustedDeviceCACertsResponseObject interface {
	VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error
}

type ImportTrustedDeviceCACerts200JSONResponse TrustedDeviceCACertsImportResult

func (response ImportTrustedDeviceCACerts200JSONResponse) VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ImportTrustedDeviceCACerts400JSONResponse struct{ externalRef0.BadRequest }

func (response ImportTrustedDeviceCACerts400JSONResponse) VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportTrustedDeviceCACerts401JSONResponse struct{ externalRef0.Unauthorized }

func (response ImportTrustedDeviceCACerts401JSONResponse) VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ImportTrustedDeviceCACerts403JSONResponse struct{ externalRef0.Forbidden }

func (response ImportTrustedDeviceCACerts403JSONResponse) VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ImportTrustedDeviceCACerts413JSONResponse externalRef0.Error

func (response ImportTrustedDeviceCACerts413JSONResponse) VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ImportTrustedDeviceCACerts500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response ImportTrustedDeviceCACerts500JSONResponse) VisitImportTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACertRequestObject struct {
	Fingerprint string `json:"fingerprint"`
}

type DeleteTrustedDeviceCACertResponseObject interface {
	VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error
}

type DeleteTrustedDeviceCACert204Response struct {
}

func (response DeleteTrustedDeviceCACert204Response) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTrustedDeviceCACert401JSONResponse struct{ externalRef0.Unauthorized }

func (response DeleteTrustedDeviceCACert401JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACert403JSONResponse struct{ externalRef0.Forbidden }

func (response DeleteTrustedDeviceCACert403JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACert404JSONResponse struct{ externalRef0.NotFound }

func (response DeleteTrustedDeviceCACert404JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACert500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response DeleteTrustedDeviceCACert500JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByFingerprintRequestObject struct {
	Fingerprint string `json:"fingerprint"`
}

type GetTrustedDeviceCACertByFingerprintResponseObject interface {
	VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error
}

type GetTrustedDeviceCACertByFingerprint200JSONResponse TrustedDeviceCACert

func (response GetTrustedDeviceCACertByFingerprint200JSONResponse) VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByFingerprint200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetTrustedDeviceCACertByFingerprint200ApplicationxPemFileResponse) VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetTrustedDeviceCACertByFingerprint401JSONResponse struct{ externalRef0.Unauthorized }

func (response GetTrustedDeviceCACertByFingerprint401JSONResponse) VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByFingerprint403JSONResponse struct{ externalRef0.Forbidden }

func (response GetTrustedDeviceCACertByFingerprint403JSONResponse) VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByFingerprint404JSONResponse struct{ externalRef0.NotFound }

func (response GetTrustedDeviceCACertByFingerprint404JSONResponse) VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByFingerprint500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response GetTrustedDeviceCACertByFingerprint500JSONResponse) VisitGetTrustedDeviceCACertByFingerprintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all trusted device CA certificates
	// (GET /device-ca)
	ListTrustedDeviceCACerts(ctx context.Context, request ListTrustedDeviceCACertsRequestObject) (ListTrustedDeviceCACertsResponseObject, error)
	// Import one or more trusted device CA certificates
	// (POST /device-ca)
	ImportTrustedDeviceCACerts(ctx context.Context, request ImportTrustedDeviceCACertsRequestObject) (ImportTrustedDeviceCACertsResponseObject, error)
	// Delete a trusted device CA certificate by fingerprint
	// (DELETE /device-ca/{fingerprint})
	DeleteTrustedDeviceCACert(ctx context.Context, request DeleteTrustedDeviceCACertRequestObject) (DeleteTrustedDeviceCACertResponseObject, error)
	// Get a trusted device CA certificate by fingerprint
	// (GET /device-ca/{fingerprint})
	GetTrustedDeviceCACertByFingerprint(ctx context.Context, request GetTrustedDeviceCACertByFingerprintRequestObject) (GetTrustedDeviceCACertByFingerprintResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListTrustedDeviceCACerts operation middleware
func (sh *strictHandler) ListTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request, params ListTrustedDeviceCACertsParams) {
	var request ListTrustedDeviceCACertsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTrustedDeviceCACerts(ctx, request.(ListTrustedDeviceCACertsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTrustedDeviceCACerts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTrustedDeviceCACertsResponseObject); ok {
		if err := validResponse.VisitListTrustedDeviceCACertsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportTrustedDeviceCACerts operation middleware
func (sh *strictHandler) ImportTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request) {
	var request ImportTrustedDeviceCACertsRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportTrustedDeviceCACerts(ctx, request.(ImportTrustedDeviceCACertsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportTrustedDeviceCACerts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportTrustedDeviceCACertsResponseObject); ok {
		if err := validResponse.VisitImportTrustedDeviceCACertsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTrustedDeviceCACert operation middleware
func (sh *strictHandler) DeleteTrustedDeviceCACert(w http.ResponseWriter, r *http.Request, fingerprint string) {
	var request DeleteTrustedDeviceCACertRequestObject

	request.Fingerprint = fingerprint

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTrustedDeviceCACert(ctx, request.(DeleteTrustedDeviceCACertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTrustedDeviceCACert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTrustedDeviceCACertResponseObject); ok {
		if err := validResponse.VisitDeleteTrustedDeviceCACertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTrustedDeviceCACertByFingerprint operation middleware
func (sh *strictHandler) GetTrustedDeviceCACertByFingerprint(w http.ResponseWriter, r *http.Request, fingerprint string) {
	var request GetTrustedDeviceCACertByFingerprintRequestObject

	request.Fingerprint = fingerprint

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrustedDeviceCACertByFingerprint(ctx, request.(GetTrustedDeviceCACertByFingerprintRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrustedDeviceCACertByFingerprint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTrustedDeviceCACertByFingerprintResponseObject); ok {
		if err := validResponse.VisitGetTrustedDeviceCACertByFingerprintResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
