package middleware

import (
	"context"
	"net/http"
	"strings"

	"github.com/elnormous/contenttype"
)

type contextKey string

const (
	contentTypeKey contextKey = "preferred-content-type"
)

// ContentNegotiationMiddleware returns a strict middleware that negotiates the
// response content type from the request's Accept header. The caller supplies
// the set of media types the endpoint can produce and a default to use when
// negotiation fails or no Accept header is present.
//
// F is the strict handler function type generated by oapi-codegen for a given
// package (each generated package defines its own StrictHandlerFunc type).
func ContentNegotiationMiddleware[F ~func(context.Context, http.ResponseWriter, *http.Request, any) (any, error)](
	availableTypes []contenttype.MediaType,
	defaultType string,
) func(f F, operationID string) F {
	type rawFunc = func(context.Context, http.ResponseWriter, *http.Request, any) (any, error)
	return func(f F, operationID string) F {
		return F(func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error) {
			preferred := defaultType
			if accept := r.Header.Get("Accept"); accept != "" {
				accepted, _, err := contenttype.GetAcceptableMediaType(r, availableTypes)
				if err == nil {
					preferred = strings.ToLower(accepted.String())
				}
			}
			ctx = context.WithValue(ctx, contentTypeKey, preferred)
			return rawFunc(f)(ctx, w, r, request)
		})
	}
}

// PreferredContentType extracts the negotiated content type from the context.
func PreferredContentType(ctx context.Context) string {
	v, _ := ctx.Value(contentTypeKey).(string)
	return v
}
