#Type Name                         ID  GECOS                         Home directory                   Shell
u     go-fdo-server-rendezvous   -   "Go FDO rendezvous server"  /run/go-fdo-server-rendezvous  -
