#Type Name                         ID  GECOS                         Home directory                   Shell
u     go-fdo-server-manufacturer   -   "Go FDO manufacturer server"  /run/go-fdo-server-manufacturer  -
