.nh
.TH "GO-FDO-SERVER" "1" "May 2026" "go-fdo-server" "Go FDO Server"

.SH NAME
go-fdo-server - Run a FIDO Device Onboard (FDO) server


.SH SYNOPSIS
\fBgo-fdo-server {manufacturing|rendezvous|owner} [flags]\fP


.SH DESCRIPTION
Run an FDO Manufacturing, Rendezvous, or Owner server.

.PP
Use one of the subcommands to run a Manufacturing, Rendezvous, or Owner
server instance. Each subcommand accepts an ip_address:port argument specifying the listen address.


.SH OPTIONS
\fB--config\fP=""
	Pathname of the configuration file

.PP
\fB--db-dsn\fP=""
	Database DSN (connection string)

.PP
\fB--db-type\fP="sqlite"
	Database type (sqlite or postgres)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for go-fdo-server

.PP
\fB--http-cert\fP=""
	Path to server certificate

.PP
\fB--http-key\fP=""
	Path to server private key

.PP
\fB--log-level\fP="info"
	Set logging level (debug, info, warn, error)


.SH EXAMPLE
.EX
  # Run a Manufacturing server on port 8038 using a configuration file:
  go-fdo-server manufacturing 0.0.0.0:8038 --config /etc/go-fdo-server/manufacturing.yaml
.EE


.SH SEE ALSO
\fBgo-fdo-server-manufacturing(1)\fP, \fBgo-fdo-server-owner(1)\fP, \fBgo-fdo-server-rendezvous(1)\fP
