# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: voucher
generate:
  std-http-server: true
  strict-server: true
  models: true
output: handler.gen.go
import-mapping:
  ../components/openapi.yaml: "github.com/fido-device-onboard/go-fdo-server/api/v2/components"
output-options:
  # to make sure that all types are generated
  skip-prune: true
