//go:build go1.22

// Package voucher provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package voucher

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/api/v2/components"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
	BasicAuthScopes  basicAuthContextKey  = "BasicAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
	Oauth2AuthScopes oauth2AuthContextKey = "Oauth2Auth.Scopes"
	OidcAuthScopes   oidcAuthContextKey   = "OidcAuth.Scopes"
)

// Defines values for HashAlgorithm.
const (
	HMACSHA256 HashAlgorithm = "HMAC-SHA-256"
	HMACSHA384 HashAlgorithm = "HMAC-SHA-384"
	HMACSHA512 HashAlgorithm = "HMAC-SHA-512"
	SHA256     HashAlgorithm = "SHA-256"
	SHA384     HashAlgorithm = "SHA-384"
	SHA512     HashAlgorithm = "SHA-512"
)

// Valid indicates whether the value is a known member of the HashAlgorithm enum.
func (e HashAlgorithm) Valid() bool {
	switch e {
	case HMACSHA256:
		return true
	case HMACSHA384:
		return true
	case HMACSHA512:
		return true
	case SHA256:
		return true
	case SHA384:
		return true
	case SHA512:
		return true
	default:
		return false
	}
}

// Defines values for PublicKeyType.
const (
	RSA2048RESTR PublicKeyType = "RSA2048RESTR"
	RSAPKCS      PublicKeyType = "RSAPKCS"
	SECP256R1    PublicKeyType = "SECP256R1"
	SECP384R1    PublicKeyType = "SECP384R1"
)

// Valid indicates whether the value is a known member of the PublicKeyType enum.
func (e PublicKeyType) Valid() bool {
	switch e {
	case RSA2048RESTR:
		return true
	case RSAPKCS:
		return true
	case SECP256R1:
		return true
	case SECP384R1:
		return true
	default:
		return false
	}
}

// Defines values for ListOwnershipVouchersParamsSortBy.
const (
	CreatedAt  ListOwnershipVouchersParamsSortBy = "createdAt"
	DeviceInfo ListOwnershipVouchersParamsSortBy = "deviceInfo"
	Guid       ListOwnershipVouchersParamsSortBy = "guid"
	UpdatedAt  ListOwnershipVouchersParamsSortBy = "updatedAt"
)

// Valid indicates whether the value is a known member of the ListOwnershipVouchersParamsSortBy enum.
func (e ListOwnershipVouchersParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case DeviceInfo:
		return true
	case Guid:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListOwnershipVouchersParamsSortOrder.
const (
	Asc  ListOwnershipVouchersParamsSortOrder = "asc"
	Desc ListOwnershipVouchersParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListOwnershipVouchersParamsSortOrder enum.
func (e ListOwnershipVouchersParamsSortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Hash defines model for Hash.
type Hash struct {
	// Algorithm Hash algorithm.
	Algorithm HashAlgorithm `json:"algorithm"`

	// Value Hexadecimal hash value. The length must match the algorithm:
	// - SHA-256/HMAC-SHA-256: 64 hexadecimal characters (32 bytes)
	// - SHA-384/HMAC-SHA-384: 96 hexadecimal characters (48 bytes)
	// - SHA-512/HMAC-SHA-512: 128 hexadecimal characters (64 bytes)
	Value string `json:"value"`
}

// HashAlgorithm Hash algorithm.
type HashAlgorithm string

// OwnershipVoucher defines model for OwnershipVoucher.
type OwnershipVoucher struct {
	// CertChain X.509 certificate chain in PEM format (null for Intel EPID).
	CertChain *[]string `json:"certChain,omitempty"`

	// DeviceInfo Device information string.
	DeviceInfo VoucherDeviceInfo `json:"deviceInfo"`

	// Entries Ownership entry chain.
	Entries []VoucherEntry `json:"entries"`

	// Guid The device GUID (32 hexadecimal characters).
	Guid   VoucherGuid   `json:"guid"`
	Header VoucherHeader `json:"header"`
	Hmac   Hash          `json:"hmac"`

	// NumEntries Number of ownership entries in the voucher.
	NumEntries VoucherNumEntries `json:"numEntries"`

	// ProtocolVersion The FDO protocol version (e.g., 101 for version 1.1).
	ProtocolVersion VoucherProtocolVersion `json:"protocolVersion"`
}

// OwnershipVoucherCreatedAt The timestamp when the voucher was created.
type OwnershipVoucherCreatedAt = time.Time

// OwnershipVoucherInfo defines model for OwnershipVoucherInfo.
type OwnershipVoucherInfo struct {
	// CreatedAt The timestamp when the voucher was created.
	CreatedAt OwnershipVoucherCreatedAt `json:"createdAt"`

	// UpdatedAt The timestamp when the voucher was last updated.
	UpdatedAt OwnershipVoucherUpdatedAt `json:"updatedAt"`
	Voucher   OwnershipVoucher          `json:"voucher"`
}

// OwnershipVoucherSummary defines model for OwnershipVoucherSummary.
type OwnershipVoucherSummary struct {
	// DeviceInfo Device information string.
	DeviceInfo VoucherDeviceInfo `json:"deviceInfo"`

	// Guid The device GUID (32 hexadecimal characters).
	Guid VoucherGuid `json:"guid"`

	// NumEntries Number of ownership entries in the voucher.
	NumEntries VoucherNumEntries `json:"numEntries"`

	// ProtocolVersion The FDO protocol version (e.g., 101 for version 1.1).
	ProtocolVersion VoucherProtocolVersion `json:"protocolVersion"`
}

// OwnershipVoucherSummaryInfo defines model for OwnershipVoucherSummaryInfo.
type OwnershipVoucherSummaryInfo struct {
	// CreatedAt The timestamp when the voucher was created.
	CreatedAt OwnershipVoucherCreatedAt `json:"createdAt"`

	// UpdatedAt The timestamp when the voucher was last updated.
	UpdatedAt OwnershipVoucherUpdatedAt `json:"updatedAt"`
	Voucher   OwnershipVoucherSummary   `json:"voucher"`
}

// OwnershipVoucherUpdatedAt The timestamp when the voucher was last updated.
type OwnershipVoucherUpdatedAt = time.Time

// OwnershipVouchersPaginated defines model for OwnershipVouchersPaginated.
type OwnershipVouchersPaginated struct {
	// Limit The number of items returned in this response.
	Limit int `json:"limit"`

	// Offset The offset from the beginning of the collection.
	Offset int `json:"offset"`

	// Total Total number of ownership vouchers available.
	Total    int                           `json:"total"`
	Vouchers []OwnershipVoucherSummaryInfo `json:"vouchers"`
}

// PublicKey defines model for PublicKey.
type PublicKey struct {
	// Type Public key algorithm type.
	Type PublicKeyType `json:"type"`

	// Value Base64-encoded public key.
	Value string `json:"value"`
}

// PublicKeyType Public key algorithm type.
type PublicKeyType string

// VoucherDeviceInfo Device information string.
type VoucherDeviceInfo = string

// VoucherEntry defines model for VoucherEntry.
type VoucherEntry struct {
	// Extra Additional optional data.
	Extra        *map[string]interface{} `json:"extra,omitempty"`
	HeaderHash   Hash                    `json:"headerHash"`
	PreviousHash Hash                    `json:"previousHash"`
	PublicKey    PublicKey               `json:"publicKey"`
}

// VoucherGuid The device GUID (32 hexadecimal characters).
type VoucherGuid = string

// VoucherHeader defines model for VoucherHeader.
type VoucherHeader struct {
	// CertChainHash Hash of the certificate chain (required when certChain is present).
	CertChainHash *Hash `json:"certChainHash,omitempty"`

	// DeviceInfo Device information string.
	DeviceInfo string `json:"deviceInfo"`

	// Guid The device GUID (32 hexadecimal characters).
	Guid            string    `json:"guid"`
	ManufacturerKey PublicKey `json:"manufacturerKey"`

	// RvInfo Rendezvous information array containing one or more instruction sets
	// (RendezvousDirective). Each instruction set guides devices and owners on how
	// to connect to the rendezvous server, including network configuration, protocols,
	// and connection parameters.
	// Processing behavior (FDO specification section 3.7):
	// - Instruction sets are processed in order (index 0 first, then 1, etc.)
	// - The first successful connection to a rendezvous server MAY be used
	// - All DNS addresses within an instruction set MUST be processed before
	//   moving to the next instruction set
	// - Multiple instruction sets provide fallback options for device connectivity
	// - Devices and owners may avoid redundant operations (e.g., contacting the
	//   same IP address twice)
	RvInfo externalRef0.RVInfo `json:"rvInfo"`

	// Version Header version.
	Version int `json:"version"`
}

// VoucherNumEntries Number of ownership entries in the voucher.
type VoucherNumEntries = int

// VoucherProtocolVersion The FDO protocol version (e.g., 101 for version 1.1).
type VoucherProtocolVersion = int

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// basicAuthContextKey is the context key for BasicAuth security scheme
type basicAuthContextKey string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// oauth2AuthContextKey is the context key for Oauth2Auth security scheme
type oauth2AuthContextKey string

// oidcAuthContextKey is the context key for OidcAuth security scheme
type oidcAuthContextKey string

// ListOwnershipVouchersParams defines parameters for ListOwnershipVouchers.
type ListOwnershipVouchersParams struct {
	// Limit The number of items to return per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Guid Filters the results by the exact device GUID.
	Guid *string `form:"guid,omitempty" json:"guid,omitempty"`

	// DeviceInfo Filters the results by device information (case-insensitive partial match).
	DeviceInfo *string `form:"deviceInfo,omitempty" json:"deviceInfo,omitempty"`

	// Search Searches within device info and GUID fields (case-insensitive).
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sorts the results by the specified field.
	SortBy *ListOwnershipVouchersParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Specifies the sorting order.
	SortOrder *ListOwnershipVouchersParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListOwnershipVouchersParamsSortBy defines parameters for ListOwnershipVouchers.
type ListOwnershipVouchersParamsSortBy string

// ListOwnershipVouchersParamsSortOrder defines parameters for ListOwnershipVouchers.
type ListOwnershipVouchersParamsSortOrder string

// ImportOwnershipVouchers201JSONResponseBody1 defines parameters for ImportOwnershipVouchers.
type ImportOwnershipVouchers201JSONResponseBody1 = []OwnershipVoucherSummaryInfo

// ImportOwnershipVouchers201JSONResponseBody defines parameters for ImportOwnershipVouchers.
type ImportOwnershipVouchers201JSONResponseBody struct {
	union json.RawMessage
}

// AsOwnershipVoucherSummaryInfo returns the union data inside the ImportOwnershipVouchers201JSONResponseBody as a OwnershipVoucherSummaryInfo
func (t ImportOwnershipVouchers201JSONResponseBody) AsOwnershipVoucherSummaryInfo() (OwnershipVoucherSummaryInfo, error) {
	var body OwnershipVoucherSummaryInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwnershipVoucherSummaryInfo overwrites any union data inside the ImportOwnershipVouchers201JSONResponseBody as the provided OwnershipVoucherSummaryInfo
func (t *ImportOwnershipVouchers201JSONResponseBody) FromOwnershipVoucherSummaryInfo(v OwnershipVoucherSummaryInfo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwnershipVoucherSummaryInfo performs a merge with any union data inside the ImportOwnershipVouchers201JSONResponseBody, using the provided OwnershipVoucherSummaryInfo
func (t *ImportOwnershipVouchers201JSONResponseBody) MergeOwnershipVoucherSummaryInfo(v OwnershipVoucherSummaryInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImportOwnershipVouchers201JSONResponseBody1 returns the union data inside the ImportOwnershipVouchers201JSONResponseBody as a ImportOwnershipVouchers201JSONResponseBody1
func (t ImportOwnershipVouchers201JSONResponseBody) AsImportOwnershipVouchers201JSONResponseBody1() (ImportOwnershipVouchers201JSONResponseBody1, error) {
	var body ImportOwnershipVouchers201JSONResponseBody1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImportOwnershipVouchers201JSONResponseBody1 overwrites any union data inside the ImportOwnershipVouchers201JSONResponseBody as the provided ImportOwnershipVouchers201JSONResponseBody1
func (t *ImportOwnershipVouchers201JSONResponseBody) FromImportOwnershipVouchers201JSONResponseBody1(v ImportOwnershipVouchers201JSONResponseBody1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImportOwnershipVouchers201JSONResponseBody1 performs a merge with any union data inside the ImportOwnershipVouchers201JSONResponseBody, using the provided ImportOwnershipVouchers201JSONResponseBody1
func (t *ImportOwnershipVouchers201JSONResponseBody) MergeImportOwnershipVouchers201JSONResponseBody1(v ImportOwnershipVouchers201JSONResponseBody1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ImportOwnershipVouchers201JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImportOwnershipVouchers201JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all ownership vouchers
	// (GET /vouchers)
	ListOwnershipVouchers(w http.ResponseWriter, r *http.Request, params ListOwnershipVouchersParams)
	// Import ownership voucher(s)
	// (POST /vouchers)
	ImportOwnershipVouchers(w http.ResponseWriter, r *http.Request)
	// Delete an ownership voucher by GUID
	// (DELETE /vouchers/{guid})
	DeleteOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string)
	// Get an ownership voucher by GUID
	// (GET /vouchers/{guid})
	GetOwnershipVoucherByGuid(w http.ResponseWriter, r *http.Request, guid string)
	// Extend an ownership voucher
	// (POST /vouchers/{guid}/extend)
	ExtendOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOwnershipVouchers operation middleware
func (siw *ServerInterfaceWrapper) ListOwnershipVouchers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOwnershipVouchersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "guid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "guid", r.URL.Query(), &params.Guid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "guid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "deviceInfo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deviceInfo", r.URL.Query(), &params.DeviceInfo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "deviceInfo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceInfo", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sortBy", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sortBy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sortOrder", r.URL.Query(), &params.SortOrder, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sortOrder"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortOrder", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOwnershipVouchers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportOwnershipVouchers operation middleware
func (siw *ServerInterfaceWrapper) ImportOwnershipVouchers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportOwnershipVouchers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOwnershipVoucher operation middleware
func (siw *ServerInterfaceWrapper) DeleteOwnershipVoucher(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOwnershipVoucher(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOwnershipVoucherByGuid operation middleware
func (siw *ServerInterfaceWrapper) GetOwnershipVoucherByGuid(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOwnershipVoucherByGuid(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExtendOwnershipVoucher operation middleware
func (siw *ServerInterfaceWrapper) ExtendOwnershipVoucher(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, OidcAuthScopes, []string{})

	ctx = context.WithValue(ctx, Oauth2AuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExtendOwnershipVoucher(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/vouchers", wrapper.ListOwnershipVouchers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/vouchers", wrapper.ImportOwnershipVouchers)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/vouchers/{guid}", wrapper.DeleteOwnershipVoucher)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/vouchers/{guid}", wrapper.GetOwnershipVoucherByGuid)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/vouchers/{guid}/extend", wrapper.ExtendOwnershipVoucher)

	return m
}

type ListOwnershipVouchersRequestObject struct {
	Params ListOwnershipVouchersParams
}

type ListOwnershipVouchersResponseObject interface {
	VisitListOwnershipVouchersResponse(w http.ResponseWriter) error
}

type ListOwnershipVouchers200JSONResponse OwnershipVouchersPaginated

func (response ListOwnershipVouchers200JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipVouchers200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ListOwnershipVouchers200ApplicationxPemFileResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ListOwnershipVouchers400JSONResponse struct {
	externalRef0.BadRequestJSONResponse
}

func (response ListOwnershipVouchers400JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipVouchers401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response ListOwnershipVouchers401JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipVouchers403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response ListOwnershipVouchers403JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipVouchers500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response ListOwnershipVouchers500JSONResponse) VisitListOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchersRequestObject struct {
	Body io.Reader
}

type ImportOwnershipVouchersResponseObject interface {
	VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error
}

type ImportOwnershipVouchers201JSONResponse = ImportOwnershipVouchers201JSONResponseBody

func (response ImportOwnershipVouchers201JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.union); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchers400JSONResponse struct {
	externalRef0.BadRequestJSONResponse
}

func (response ImportOwnershipVouchers400JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchers401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response ImportOwnershipVouchers401JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchers403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response ImportOwnershipVouchers403JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchers409JSONResponse externalRef0.Error

func (response ImportOwnershipVouchers409JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchers413JSONResponse struct {
	externalRef0.PayloadTooLargeJSONResponse
}

func (response ImportOwnershipVouchers413JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ImportOwnershipVouchers500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response ImportOwnershipVouchers500JSONResponse) VisitImportOwnershipVouchersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOwnershipVoucherRequestObject struct {
	Guid string `json:"guid"`
}

type DeleteOwnershipVoucherResponseObject interface {
	VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error
}

type DeleteOwnershipVoucher204Response struct {
}

func (response DeleteOwnershipVoucher204Response) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOwnershipVoucher401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response DeleteOwnershipVoucher401JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOwnershipVoucher403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response DeleteOwnershipVoucher403JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOwnershipVoucher404JSONResponse struct {
	externalRef0.NotFoundJSONResponse
}

func (response DeleteOwnershipVoucher404JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOwnershipVoucher500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response DeleteOwnershipVoucher500JSONResponse) VisitDeleteOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOwnershipVoucherByGuidRequestObject struct {
	Guid string `json:"guid"`
}

type GetOwnershipVoucherByGuidResponseObject interface {
	VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error
}

type GetOwnershipVoucherByGuid200JSONResponse OwnershipVoucher

func (response GetOwnershipVoucherByGuid200JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOwnershipVoucherByGuid200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOwnershipVoucherByGuid200ApplicationxPemFileResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetOwnershipVoucherByGuid401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response GetOwnershipVoucherByGuid401JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOwnershipVoucherByGuid403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response GetOwnershipVoucherByGuid403JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOwnershipVoucherByGuid404JSONResponse struct {
	externalRef0.NotFoundJSONResponse
}

func (response GetOwnershipVoucherByGuid404JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOwnershipVoucherByGuid500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response GetOwnershipVoucherByGuid500JSONResponse) VisitGetOwnershipVoucherByGuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ExtendOwnershipVoucherRequestObject struct {
	Guid string `json:"guid"`
	Body io.Reader
}

type ExtendOwnershipVoucherResponseObject interface {
	VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error
}

type ExtendOwnershipVoucher200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExtendOwnershipVoucher200ApplicationxPemFileResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExtendOwnershipVoucher400JSONResponse struct {
	externalRef0.BadRequestJSONResponse
}

func (response ExtendOwnershipVoucher400JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ExtendOwnershipVoucher401JSONResponse struct {
	externalRef0.UnauthorizedJSONResponse
}

func (response ExtendOwnershipVoucher401JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ExtendOwnershipVoucher403JSONResponse struct {
	externalRef0.ForbiddenJSONResponse
}

func (response ExtendOwnershipVoucher403JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExtendOwnershipVoucher404JSONResponse struct {
	externalRef0.NotFoundJSONResponse
}

func (response ExtendOwnershipVoucher404JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ExtendOwnershipVoucher413JSONResponse struct {
	externalRef0.PayloadTooLargeJSONResponse
}

func (response ExtendOwnershipVoucher413JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ExtendOwnershipVoucher500JSONResponse struct {
	externalRef0.InternalServerErrorJSONResponse
}

func (response ExtendOwnershipVoucher500JSONResponse) VisitExtendOwnershipVoucherResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all ownership vouchers
	// (GET /vouchers)
	ListOwnershipVouchers(ctx context.Context, request ListOwnershipVouchersRequestObject) (ListOwnershipVouchersResponseObject, error)
	// Import ownership voucher(s)
	// (POST /vouchers)
	ImportOwnershipVouchers(ctx context.Context, request ImportOwnershipVouchersRequestObject) (ImportOwnershipVouchersResponseObject, error)
	// Delete an ownership voucher by GUID
	// (DELETE /vouchers/{guid})
	DeleteOwnershipVoucher(ctx context.Context, request DeleteOwnershipVoucherRequestObject) (DeleteOwnershipVoucherResponseObject, error)
	// Get an ownership voucher by GUID
	// (GET /vouchers/{guid})
	GetOwnershipVoucherByGuid(ctx context.Context, request GetOwnershipVoucherByGuidRequestObject) (GetOwnershipVoucherByGuidResponseObject, error)
	// Extend an ownership voucher
	// (POST /vouchers/{guid}/extend)
	ExtendOwnershipVoucher(ctx context.Context, request ExtendOwnershipVoucherRequestObject) (ExtendOwnershipVoucherResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListOwnershipVouchers operation middleware
func (sh *strictHandler) ListOwnershipVouchers(w http.ResponseWriter, r *http.Request, params ListOwnershipVouchersParams) {
	var request ListOwnershipVouchersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOwnershipVouchers(ctx, request.(ListOwnershipVouchersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOwnershipVouchers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOwnershipVouchersResponseObject); ok {
		if err := validResponse.VisitListOwnershipVouchersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportOwnershipVouchers operation middleware
func (sh *strictHandler) ImportOwnershipVouchers(w http.ResponseWriter, r *http.Request) {
	var request ImportOwnershipVouchersRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportOwnershipVouchers(ctx, request.(ImportOwnershipVouchersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportOwnershipVouchers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportOwnershipVouchersResponseObject); ok {
		if err := validResponse.VisitImportOwnershipVouchersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOwnershipVoucher operation middleware
func (sh *strictHandler) DeleteOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string) {
	var request DeleteOwnershipVoucherRequestObject

	request.Guid = guid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOwnershipVoucher(ctx, request.(DeleteOwnershipVoucherRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOwnershipVoucher")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOwnershipVoucherResponseObject); ok {
		if err := validResponse.VisitDeleteOwnershipVoucherResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOwnershipVoucherByGuid operation middleware
func (sh *strictHandler) GetOwnershipVoucherByGuid(w http.ResponseWriter, r *http.Request, guid string) {
	var request GetOwnershipVoucherByGuidRequestObject

	request.Guid = guid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOwnershipVoucherByGuid(ctx, request.(GetOwnershipVoucherByGuidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOwnershipVoucherByGuid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOwnershipVoucherByGuidResponseObject); ok {
		if err := validResponse.VisitGetOwnershipVoucherByGuidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExtendOwnershipVoucher operation middleware
func (sh *strictHandler) ExtendOwnershipVoucher(w http.ResponseWriter, r *http.Request, guid string) {
	var request ExtendOwnershipVoucherRequestObject

	request.Guid = guid

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExtendOwnershipVoucher(ctx, request.(ExtendOwnershipVoucherRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExtendOwnershipVoucher")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExtendOwnershipVoucherResponseObject); ok {
		if err := validResponse.VisitExtendOwnershipVoucherResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
