//go:build go1.22

// Package voucher provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package voucher

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/api/v1/components"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// VoucherMetadata Ownership voucher metadata (excludes CBOR data)
type VoucherMetadata struct {
	// CreatedAt Timestamp when voucher was first inserted
	CreatedAt time.Time `json:"created_at"`

	// DeviceInfo Device information string
	DeviceInfo string `json:"device_info"`

	// Guid Device GUID (hex-encoded)
	Guid string `json:"guid"`

	// UpdatedAt Timestamp when voucher was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// ListVouchersParams defines parameters for ListVouchers.
type ListVouchersParams struct {
	// Guid Filter by device GUID (hex-encoded)
	Guid *string `form:"guid,omitempty" json:"guid,omitempty"`

	// DeviceInfo Filter by device info string
	DeviceInfo *string `form:"device_info,omitempty" json:"device_info,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Query ownership vouchers (Deprecated)
	// (GET /vouchers)
	ListVouchers(w http.ResponseWriter, r *http.Request, params ListVouchersParams)
	// Insert ownership voucher(s) (Deprecated)
	// (POST /vouchers)
	InsertVoucher(w http.ResponseWriter, r *http.Request)
	// Get ownership voucher by GUID (Deprecated)
	// (GET /vouchers/{guid})
	GetVoucherByGUID(w http.ResponseWriter, r *http.Request, guid string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVouchers operation middleware
func (siw *ServerInterfaceWrapper) ListVouchers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVouchersParams

	// ------------- Optional query parameter "guid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "guid", r.URL.Query(), &params.Guid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	// ------------- Optional query parameter "device_info" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "device_info", r.URL.Query(), &params.DeviceInfo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_info", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVouchers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InsertVoucher operation middleware
func (siw *ServerInterfaceWrapper) InsertVoucher(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InsertVoucher(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVoucherByGUID operation middleware
func (siw *ServerInterfaceWrapper) GetVoucherByGUID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", r.PathValue("guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVoucherByGUID(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/vouchers", wrapper.ListVouchers)
	m.HandleFunc("POST "+options.BaseURL+"/vouchers", wrapper.InsertVoucher)
	m.HandleFunc("GET "+options.BaseURL+"/vouchers/{guid}", wrapper.GetVoucherByGUID)

	return m
}

type ListVouchersRequestObject struct {
	Params ListVouchersParams
}

type ListVouchersResponseObject interface {
	VisitListVouchersResponse(w http.ResponseWriter) error
}

type ListVouchers200JSONResponse []VoucherMetadata

func (response ListVouchers200JSONResponse) VisitListVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVouchers400TextResponse externalRef0.ErrorString

func (response ListVouchers400TextResponse) VisitListVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type ListVouchers500TextResponse externalRef0.ErrorString

func (response ListVouchers500TextResponse) VisitListVouchersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type InsertVoucherRequestObject struct {
	Body io.Reader
}

type InsertVoucherResponseObject interface {
	VisitInsertVoucherResponse(w http.ResponseWriter) error
}

type InsertVoucher200TextResponse string

func (response InsertVoucher200TextResponse) VisitInsertVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type InsertVoucher400TextResponse externalRef0.ErrorString

func (response InsertVoucher400TextResponse) VisitInsertVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type InsertVoucher413TextResponse externalRef0.ErrorString

func (response InsertVoucher413TextResponse) VisitInsertVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(413)

	_, err := w.Write([]byte(response))
	return err
}

type InsertVoucher500TextResponse externalRef0.ErrorString

func (response InsertVoucher500TextResponse) VisitInsertVoucherResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type GetVoucherByGUIDRequestObject struct {
	Guid string `json:"guid"`
}

type GetVoucherByGUIDResponseObject interface {
	VisitGetVoucherByGUIDResponse(w http.ResponseWriter) error
}

type GetVoucherByGUID200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetVoucherByGUID200ApplicationxPemFileResponse) VisitGetVoucherByGUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetVoucherByGUID400TextResponse externalRef0.ErrorString

func (response GetVoucherByGUID400TextResponse) VisitGetVoucherByGUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetVoucherByGUID404TextResponse externalRef0.ErrorString

func (response GetVoucherByGUID404TextResponse) VisitGetVoucherByGUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type GetVoucherByGUID500TextResponse externalRef0.ErrorString

func (response GetVoucherByGUID500TextResponse) VisitGetVoucherByGUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Query ownership vouchers (Deprecated)
	// (GET /vouchers)
	ListVouchers(ctx context.Context, request ListVouchersRequestObject) (ListVouchersResponseObject, error)
	// Insert ownership voucher(s) (Deprecated)
	// (POST /vouchers)
	InsertVoucher(ctx context.Context, request InsertVoucherRequestObject) (InsertVoucherResponseObject, error)
	// Get ownership voucher by GUID (Deprecated)
	// (GET /vouchers/{guid})
	GetVoucherByGUID(ctx context.Context, request GetVoucherByGUIDRequestObject) (GetVoucherByGUIDResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListVouchers operation middleware
func (sh *strictHandler) ListVouchers(w http.ResponseWriter, r *http.Request, params ListVouchersParams) {
	var request ListVouchersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVouchers(ctx, request.(ListVouchersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVouchers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVouchersResponseObject); ok {
		if err := validResponse.VisitListVouchersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InsertVoucher operation middleware
func (sh *strictHandler) InsertVoucher(w http.ResponseWriter, r *http.Request) {
	var request InsertVoucherRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InsertVoucher(ctx, request.(InsertVoucherRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InsertVoucher")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InsertVoucherResponseObject); ok {
		if err := validResponse.VisitInsertVoucherResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVoucherByGUID operation middleware
func (sh *strictHandler) GetVoucherByGUID(w http.ResponseWriter, r *http.Request, guid string) {
	var request GetVoucherByGUIDRequestObject

	request.Guid = guid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVoucherByGUID(ctx, request.(GetVoucherByGUIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVoucherByGUID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVoucherByGUIDResponseObject); ok {
		if err := validResponse.VisitGetVoucherByGUIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
